name: 'Pipe to Release'
description: 'Upload assets to an existing release or create a new one.'
author: 'KotwOSS'
branding:
  icon: 'arrow-up-right'
  color: 'green'
inputs:
  token:
    required: true
    description: 'The token this action uses to contact the github api.'

  filemap:
    required: true
    description: 'The list of files that will be uploaded. See <a href="#file-piper">FilePiper</a> for more information.'

  repository:
    required: false
    description: 'The repository where the release will be created it.'

  skip_errors:
    required: false
    description: 'If true, the action will skip errors instead of setting the build to failed.'

  draft:
    required: false
    description: 'If true, the action will create a draft release. (Not published)'

  prerelease:
    required: false
    description: 'If true, the action will creae a prerelease.'

  overwrite:
    required: false
    description: 'If true, the action will update already existing assets instead of throwing an error'

  tag:
    required: false
    description: 'The tag of the release.'

  release_name:
    required: false
    description: 'The name of the release.'

  release_body:
    required: false
    description: 'The body (description) of the release. '

runs:
  using: 'node12'
  main: 'dist/index.js'
